website/views.py
# stores standard routes for website
# ie. where users can go to 
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, send_file
from flask_login import login_required, current_user
from .models import Note
from . import db, form_autofill
import json, os

from backend.shipping_objects import *

debugging = False
saver = SaveData()
session = saver.load_data(debugging=debugging)
shipment = session.active_shipment


print('---------RESTARTING VIEWS')
# blueprint defines a bunch of URLs
# naming it 'views' is optional but simplifies things
views = Blueprint('views', __name__)

# define route for homepage
# home() will run whenever user goes to homepage
# (ie. root directory '/')
# view orders from here
@views.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        pass
    # applies html template to homepage
    # passes user as a variable to be used in template
    return render_template("home.html", shipment=shipment, package_num=shipment.package_num)

@views.route('/upload', methods=['GET', 'POST'])
def upload_data():
    global session
    global shipment
    if request.method == 'POST':
        # Check if a file was submitted
        if 'file' not in request.files:
            print('NO FILE PART FOUND')
            return "No file part found", 400
        
        file = request.files['file']

        if file.filename == '':
            print('NO SELECTED FILE')
            return "No selected file", 400
        
        #if file and file.filename:
        try:
            # Unpickle the file and check if it is a valid Shipment object
            session = pickle.load(file)
            shipment = session.active_shipment

            flash('Session data uploaded', category='success')
            return redirect(url_for('views.home'))

        except pickle.UnpicklingError:
            return "Error unpickling the file. File upload failed."

        return "No file selected. File upload failed."
    elif request.method == 'GET':
        return render_template("upload.html")

@views.route('/export-data', methods=['GET'])
def export_data():
    file_path = saver.file_path
    print(f'EXPORT DATA FILEPATH: {file_path}')
    saver.export_data(session, export_current_data=True)
    return send_file(file_path, as_attachment=True)

@views.route('/delete-package', methods=['POST'])
def delete_package():
    # request is sent as data parameter of request object (not form)
    # request.data is json string sent from index.js
    pk_object = json.loads(request.data)    # js object defined in index.js
    print(f'----------PK OBJECT FROM DELETE: {pk_object}')
    pk_id = pk_object['pk_id']
    delete_type = pk_object['delete_type']
    
    if delete_type == 'from_box':
        for cons_pk in shipment.packages:
            if isinstance(cons_pk, ConsolidatedPackage):
                for pkkk in cons_pk.packages:
                    if str(pkkk.package_id) == str(pk_id):
                        pk = pkkk
                        cons_pk.remove_packages(packages=[pk])
                        break

    else:
        pk = shipment.package(pk_id)    # retrieves package based on id
        print(f'REMOVE PERMANENTLY FROM SHIPMENT: {pk}')
        pk.customer_order.remove_package(pk)
    saver.save_data(session)
    #pk.__class__ == 'ConsolidatedPackage'

    return jsonify({})  # jsonify empty python dictionary

@views.route('/consolidate-packages', methods=['POST'])
def consolidate():
    # request is sent as data parameter of request object (not form)
    # request.data is json string sent from index.js
    pk_ids = json.loads(request.data)    # js object defined in index.js
    shipment.consolidate([0, 0, 0], pk_ids)
    #saver.save_data(session)
    return jsonify({})

# VIEW/EDIT PACKAGE INFO HERE
# consignee/consignee info: name, email, phone, address
# additional info: has batteries, wants insurance
@views.route('/pkg/<string:pk_id>', methods=['GET', 'POST'])
def pk_details(pk_id):
    # pk_id is passed as a string
    package = shipment.package(pk_id)
    if request.method == 'POST':
        form_data = request.form
            # ASSUMES THAT SHIPPER == CUSTOMER
        # user edits shipper from view order page
        #if form_data['save_btn'] == 'shipper-info':
        #    form_autofill.assign_customer_info(package.customer, form_data)
        
        if form_data['save_btn'] == 'consignee-info':
            form_autofill.assign_consignee_info(form_data, consignee=package.consignee)
        elif form_data['save_btn'] == 'additional-info':
            form_autofill.assign_package_info(package, form_data)
            saver.save_data(session)
            return redirect(url_for('views.home'))
        elif form_data['save_btn'] == 'add-cons-package':
            pass
        else:
            raise ValueError("Do not recognize save button value, check pk_details.html")

    cons_packages = None
    if isinstance(package, ConsolidatedPackage):
        cons_packages = []
        for pk in package.packages:
            cons_packages.append(pk)

    return render_template('pk_details.html', pk=package, cons_packages=cons_packages, packages=shipment.packages)

@views.route('/add-package', methods=['GET', 'POST'])
def add_package():
    print(f'-------------request args: {request.args}')
    order_id = request.args['order_id']
    order = shipment.get_order(order_id)

    if request.method == 'POST':
        form_data = request.form
        print(f'adding package with data: {form_data}')
        
        consignee = Consignee("", "", "", "", "", "", "")
        form_autofill.assign_consignee_info(form_data, consignee=consignee)
        pk = Package(("", "", ""), "INCH", "", order, order.customer, consignee, "", "")
        form_autofill.assign_package_info(pk, form_data)
        
        return redirect(url_for('views.view_order', order_id=order.id))
    else:
        consignee = None
        if len(order.packages) > 0:
            consignee = order.packages[len(order.packages)-1].consignee
        data = form_autofill.get_autofill_dict(order=order, consignee=consignee)

        return render_template('add_package.html', order=order, data=data, consignee=consignee)
    

@views.route('/view-order', methods=['GET', 'POST'])
def view_order():
    order_id = request.args['order_id']
    order = shipment.get_order(order_id)
    
    if request.method == 'POST':
        form_data = request.form
        print(form_data)
        if form_data['save_btn'] == 'order-info':
            form_autofill.assign_customer_info(order.customer, form_data)
            form_autofill.update_order_details(order, form_data)
        elif form_data['save_btn'] == 'delete-order':
            print('deleting order')
            shipment.remove_from_shipment(order)
            flash('Order removed', category='success')
            return render_template("home.html", shipment=shipment, package_num=shipment.package_num)
        
    data = form_autofill.get_autofill_dict(order=order)
    return render_template('view_order.html', order=order, data=data)

@views.route('/add-order', methods=['GET', 'POST'])
def add_order():
    global shipment
    global debugging
    form_autofill.google_login()
    if request.method == 'POST':
        form_data = request.form
        action = form_data.get('action')

        customer = None
        # NOTE: 
        # default unit for weight is kg
        # delivery address == consignee address
        # fragile option doesn't do anything; need to add to shipping_objects
        if action == 'add':
            box_num = form_data.get('box-count')
            if int(box_num) < 1 or box_num is None:
                error_message = "Please enter a valid number of boxes (greater than 0)."
                flash(error_message, category='error')
            else:
                # assumes shipper = customer
                customer = Customer(
                    name=form_data['shipper-name'], 
                    address=form_data['shipper-address'], 
                    city=form_data['shipper-city'], 
                    state=form_data['shipper-state'], 
                    zip_code=form_data['shipper-zip'], 
                    phone=form_data['shipper-phone'], 
                    email=form_data['shipper-email'])
                shipper = Shipper(
                    name=form_data['shipper-name'], 
                    address=form_data['shipper-address'], 
                    city=form_data['shipper-city'], 
                    state=form_data['shipper-state'], 
                    zip_code=form_data['shipper-zip'], 
                    phone=form_data['shipper-phone'], 
                    email=form_data['shipper-email'])
                consignee = Consignee(
                    name=form_data['consignee-name'], 
                    address=form_data['consignee-address'], 
                    city=form_data['consignee-city'], 
                    state=form_data['consignee-state'], 
                    zip_code=form_data['consignee-zip'], # returns blank string if nothing there
                    phone=form_data['consignee-phone'], 
                    email=form_data['consignee-email'])
                
                pickup_address = None
                if form_data.get('office-drop-off') == 'drop-off':
                    office_dropoff = True
                else:
                    office_dropoff = False
                    pickup_address = form_data.get('pickup-address')
                # delivery address is consignee address by default
                office_pickup = form_data.get('office-pickup') == 'pick-up'
                insurance = form_data.get('insurance') == 'on' 
                notes = form_data.get('order-notes')
                print(f'notes: {notes}')
                order = CustomerOrder(customer, "", office_dropoff, office_pickup, insurance, notes=notes)
                order.pickup_address = pickup_address

website/templates/add_package.html
<!-- extend base template-->
{% extends "base.html" %} {% block title %}Add Package{% endblock %}

{% block style %}
<!-- aligns text boxes -->
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block content %}
<h1 align="center">Add Package for {{order.customer.name}}</h1>
<br />
<br />
<!--- #region list orders -->
<ul class="list-group list-group-flush" id="notes">
  <form class="edit-form" id="consignee-form" method="POST" action="{{ url_for('views.add_package', order_id=order.id) }}">
  <div class="form-section">
    <h3>Consignee</h3>
      <div class="form-group">
        <label for="consignee-name">Name:</label>
        <input type="text" class="form-control" id="consignee-name" name="consignee_name" value="{{data['consignee_name']}}">
      </div>
      <div class="form-group">
        <label for="consignee-email">Email:</label>
        <input type="text" class="form-control" id="consignee-email" name="consignee_email" value="{{data['consignee_email']}}">
      </div>
      <div class="form-group">
        <label for="consignee-phone">Phone Number:</label>
        <input type="text" class="form-control" id="consignee-phone" name="consignee_phone" value="{{data['consignee_phone']}}">
      </div>
      <div class="form-group">
        <label for="consignee-address">Address:</label>
        <input type="text" class="form-control" id="consignee-address" name="consignee_address" value="{{data['consignee_address']}}">
      </div>
      <div class="form-group">
        <label for="consignee-city">City:</label>
        <input type="text" class="form-control" id="consignee-city" name="consignee_city" value="{{data['consignee_city']}}">
      </div>
      <div class="form-group">
        <label for="consignee-name">State/Province:</label>
        <input type="text" class="form-control" id="consignee-state" name="consignee_state" value="{{data['consignee_state']}}">
      </div>
      <div class="form-group">
        <label for="consignee-name">Zip Code:</label>
        <input type="text" class="form-control" id="consignee-zip" name="consignee_zip" value="{{data['consignee_zip_code']}}">
      </div>
  </div>
  <div class="form-section">
    <h3>Package Details</h3>
      <div class="form-section">
        <label for="dimensions">Dimensions:</label>
        <div class="inline-inputs">
          <div class="input-group">
            <input type="text" id="length" name="length" placeholder="Length" 
              class="form-control small-input" required
            >
            <input type="text" id="width" name="width" placeholder="Width" 
             class="form-control small-input" required
            >
            <input type="text" id="height" name="height" placeholder="Height" 
              class="form-control small-input" required
            >
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="units" id="inch" 
              value="INCH" required
            >
            <label class="form-check-label" for="inch">Inches</label>
          </div>
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="units" id="cm" 
              value="CM" required
            >
            <label class="form-check-label" for="cm">CM</label>
          </div>
        </div>
      </div>

      <div class="form-section">
        <label for="weight">Weight:</label>
        <div class="inline-inputs">
          <input type="text" id="weight" name="weight" placeholder="Weight" class="form-control small-input"
          required
          >
        </div>
      </div>
      
      <div class="form-section">
        <label for="box-cargo-description">Cargo Description</label>
        <textarea id="box-cargo-description" name="package_description" required></textarea>
      </div>
      
      <div class="form-section">
        <span>
          <i class="fa-solid fa-battery-full"></i>
        </span>
        <label for="box-lithium-batteries"><strong>This box contains lithium batteries: </strong></label>
        <input type="checkbox" id="box-lithium-batteries" name="lithium_batteries">
        <p>Lithium batteries can be found in laptops, phones, and any rechargeable device.</p>
      </div>
      <div class="form-section">
        <span>
          <i class="fa-solid fa-house-crack"></i>
        </span>
        <label for="box-fragile"><strong>This package is fragile:</strong></label>
        <input type="checkbox" id="box-fragile" name="is_fragile">
      </div>
    </div>
    <button type="submit" name="save_btn" class="save-btn" value="additional-info">Save</button>
  </div>
  </form>
</ul>

<!-- #endregion -->
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- import bootstrap-->
    <!-- link to CDN (content delivery network)-->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      crossorigin="anonymous"
    />

    {% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% endblock %}

    <!-- can enclose python code or blocks-->
    <!-- blocks define a parent template that can be overwritten by children-->
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="Home" href="/">Home</a>
          <a class="nav-item nav-link" id="addOrder" href="{{ url_for('views.add_order') }}">Add Order</a>
          <a class="nav-item nav-link" id="exportExcel" href="{{ url_for('views.download_excel') }}">Download as Excel Sheet</a>
          <a class="nav-item nav-link" id="showUpload" href="{{ url_for('views.upload_data') }}">Import Data</a>
          <a class="nav-item nav-link" id="exportData" href="{{ url_for('views.export_data') }}">Export Data</a>
        </div>
      </div>
    </nav>

      <!-- show flash messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
      <div class='alert alert-danger alert-dismissable fade show' role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% elif category == 'success' %}
      <div class='alert alert-success alert-dismissable fade show' role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <!-- #region scripts -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    ></script>
    <!-- #endregion -->

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block style %}
<!-- aligns text boxes -->
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block content %}
<br />
<h1 align="center">Shipment Overview</h1>
<br />
<div class="shipment-summary">
  <p>Number of packages: {{shipment.package_num}}</p>
  <p>Number of packages with batteries: {{shipment.battery_num}}</p>
  <p>Gross Weight (kg): {{shipment.gross_weight}}</p>
  <p>Volumetric Weight (CBM): {{shipment.volumetric_weight}}</p>
</div>

<div class="sidebar">
  <h2>Consolidate Boxes</h2>
  <div class="select-btn">
    <span class="btn-text">Select Box</span>
    <span class="arrow-dwn">
      <i class="fa-solid fa-chevron-down"></i>
    </span>
  </div>
  <ul class="list-items">
    <!-- list of boxes to consolidate goes here -->
    <div id="boxes-consolidate"></div>
    <div class="consolidated-dimensions">
      <input type="text" id="length-cons" name="length-cons" placeholder="Length" 
        class="form-control small-input consolidate"
        required
      >
      <input type="text" id="width-cons" name="width-cons" placeholder="Width" 
      class="form-control small-input consolidate"
      required
      >
      <input type="text" id="height-cons" name="height-cons" placeholder="Height" 
        class="form-control small-input consolidate"
        required
      >
    </div>
  </ul>

  <button 
    class="save-btn"
    onClick="if (this.classList.contains('consolidate')) {
        consolidate(); 
      }"
    >
    Consolidate Boxes
  </button>
</div>

<button class="view-btn" onclick="showView('packageView')" align="center">Package View</button>
<button class="view-btn" onclick="showView('orderView')" align="center">Order View</button>
<br />


<div id="packageView" class="view active">
  <!-- Content for Package View -->
  <h2>Package Information</h2>
  <p>This is the package view content.</p>

  <ul class="list-group list-group-flush" id="packages">
    {% for pk in shipment.packages %}
    <li class="list-group-item">
      <div class="order-info toggle-section"
          onClick="toggleView('packageview-{{ pk.package_id }}')">
        <a href="{{ url_for('views.pk_details', pk_id=pk.package_id) }}">
          {{"Box " ~ pk.package_id}}
        </a>
        {% if pk.has_batteries %}
        <span>
          <i class="fa-solid fa-battery-full"></i>
        </span>
        {% endif %}
        {% if pk.fragile %}
        <span>
          <i class="fa-solid fa-house-crack"></i>
        </span>
        {% endif %}
        <span class="description">{{"— " ~ pk.shipper.name}}</span>
        {% if pk.validate() != True %}
        <i class="fa-solid fa-circle-exclamation"
        title="Missing the following details: {{pk.validate()}}"
        ></i>
        <span class="description"></span>
        {% endif %}
        <span class="actions">
          <a href="javascript:void(0);" onClick="delete_package('{{pk.package_id}}', 'permanent')">Delete</a>
        </span>
      </div>
      
      <div id="packageview-{{ pk.package_id }}" class="view-form" style="display: none;">
        <p>Description: {{ pk.description }}</p>
        <p>Dimensions: {{ pk.view_dimensions() }} {{pk.dim_units}}</p>
        <p>Weight: {{ pk.weight }} kg</p>
        
        <!-- these are not showing properly -->
        {% if pk.packages is defined %}
          {% for box in pk.packages %}
          {% set pk_id = box.package_id %}
          <div class="order-info toggle-section"
            onClick="toggleView('packageview-{{ pk_id }}')">
            <a href="{{ url_for('views.pk_details', pk_id=pk_id) }}">{{"Box " ~ pk_id}}</a>
            {% if pk.has_batteries %}
            <span>
              <i class="fa-solid fa-battery-full"></i>
            </span>
            {% endif %}
            {% if pk.fragile %}
            <span>
              <i class="fa-solid fa-house-crack"></i>
            </span>
            {% endif %}
            <span class="description">{{"— " ~ box.shipper.name}}</span>
            <span class="actions">
              <a href="javascript:void(0);" onClick="delete_package('{{ pk_id }}')">Delete</a>
            </span>
          </div>
          <div id="packageview-{{ pk_id }}" class="view-form" style="display: none;">
            <strong> This box is consolidated. </strong>
            <p>Description: {{ box.description }}</p>
            <p>Dimensions: {{ box.view_dimensions() }} {{box.dim_units}}</p>
            <p>Weight: {{ box.weight }} kg</p>
          </div>
          
          {% endfor %}
        {% endif %}

      </div>
    </li>
    {% endfor %}
  </ul>
</div>

<div id="orderView" class="view">
  <!-- Content for Order View -->
  <h2>Order Information</h2>
  <p>This is the order view content.</p>
  <ul class="list-group list-group-flush" id="packages">
    {% for order in shipment.orders %}
    <li class="list-group-item">
      <div class="order-info">
        <a href="{{ url_for('views.view_order', order_id=order.id) }}">
          {{ order.customer.name }}
        </a>
        <span class="description">{{" — " ~ order.packages|length ~ " packages" }}</span>
        <span class="actions">
          <a href="{{ url_for('views.add_package', order_id=order.id) }}" class="btn btn-link">Add Package</a>
        </span>
      </div>

      <br>
      <ul class="list-group list-group-flush" id="packages">
        {% for pk in order.packages %}
        <div class="order-info toggle-section"
          onClick="toggleView('orderview-{{ pk.package_id }}')">

          <a href="{{ url_for('views.pk_details', pk_id=pk.package_id) }}">
            {{"Box " ~ pk.package_id}}
          </a>
          {% if pk.has_batteries %}
          <span>
            <i class="fa-solid fa-battery-full"></i>
          </span>
          {% endif %}
          {% if pk.fragile %}
          <span>
            <i class="fa-solid fa-house-crack"></i>
          </span>
          {% endif %}
          <span class="description">{{"— " ~ pk.description}}</span>
          <span class="actions">
            <a href="javascript:void(0);" onClick="delete_package('{{pk.package_id}}', 'permanent')">Delete</a>
          </span>
          
        </div>
        <div id="orderview-{{ pk.package_id }}" class="view-form" style="display: none;">
          {% if pk.consolidated %}
          <strong> This box is consolidated. </strong>
          {% endif %}
          <p>Dimensions: {{ pk.dimensions }} {{pk.dim_units}}</p>
          <p>Weight (kg): {{ pk.weight }}</p>
        </div>
        {% endfor %}
      </ul>
    </li>
    {% endfor %}
  </ul>
</div>

<script>

// for toggling view of package
document.addEventListener('DOMContentLoaded', function() {
    // Find all elements with the class 'clickable-div'
    var viewable_sections = document.querySelectorAll('.toggle-section');
    
    // Attach a click event listener to each clickable div
    viewable_sections.forEach(function(div) {
        div.addEventListener('click', function(event) {
            // prevents links within div from working
            //event.preventDefault();
            
            // Get the value for the toggleView function from the data attribute
            var toggleValue = div.getAttribute('id');
            
            // Call the toggleView function with the provided value
            toggleView(toggleValue);
        });
    });
});

// for toggling between package and order view
function showView(viewId) {
    // Hide all views first
    const views = document.getElementsByClassName('view');
    for (let i = 0; i < views.length; i++) {
        views[i].classList.remove('active');
    }

    // Show the selected view
    document.getElementById(viewId).classList.add('active');
}

const selectBtn = document.querySelector(".select-btn"),
      saveBtn = document.querySelector(".save-btn"),
      cnsDim = document.querySelector(".consolidated-dimensions");
let items = document.querySelectorAll(".item");

selectBtn.addEventListener('click', () =>{
  selectBtn.classList.toggle('open');
})

function toggleChecked(item) {
  item.classList.toggle('checked');
  let checked = document.querySelectorAll('.checked');
  let btnText = document.querySelector('.btn-text');

  // minimum number of boxes to consolidate is now one
  // this way, large boxes get labelling priority
  if (checked.length >= 1) {
    btnText.innerText = `${checked.length} boxes selected`;
    if (!saveBtn.classList.contains('consolidate')) {
      saveBtn.classList.add('consolidate');
      cnsDim.classList.add('consolidate');
    }
  } else {
    if (checked.length == 1) {
      btnText.innerText = "Select A Second Box";
    } else {
      btnText.innerText = "Select Box";
    }
    if (saveBtn.classList.contains('consolidate')) {
      saveBtn.classList.remove('consolidate');
      cnsDim.classList.remove('consolidate');
    }
  }
}

function attachEventListeners() {
  items = document.querySelectorAll(".item");
  items.forEach(item => {
    item.addEventListener('click', () => {
      toggleChecked(item);
    });
  });
}


function box_dropdowns() {
  var box_num = {{ shipment.package_num }};
  var box_ids = {{ shipment.package_id_list|tojson }}
  let boxSectionHTML = "";

  for (let i = 0; i < box_num; i++) {
    boxSectionHTML += `
    <li class="item" value="${box_ids[i]}">
      <span class="checkbox">
        <i class="fa-solid fa-check check-icon"></i>
      </span>
      <span class="item-text">Box ${box_ids[i]}</span>
    </li>
    `;
  }

  document.getElementById("boxes-consolidate").innerHTML = boxSectionHTML;
  attachEventListeners();
};

box_dropdowns();

function consolidate() {
  // sends post request to delete-note endpoint
  console.log('consolidating');

  // which items are checked
  items = document.querySelectorAll(".item");
  checked_items = []
  items.forEach(item => {
    if (item.classList.contains('checked')) {
      val = item.getAttribute('value')
      console.log(val);
      checked_items.push(val)
    }
  });

  // FIXME send dimensions to consolidate_package in index.js
  // not sure how to fetch value from length object
  length = document.getElementById("length-cons");
  width = document.getElementById("width-cons");
  height = document.getElementById("height-cons");
  console.log('length of consolidated box:');
  console.log(length);
  consolidate_package(checked_items);
}

</script>
  
{% endblock %}

website/templates/login.html
<!-- extend base template-->
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
    placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/signup.html
<!-- extend base template-->
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
    placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Confirm password</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
    placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/upload.html
<!-- extend base template-->
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<div class="upload">
  <br>
  <br>
  <h3>Upload Data</h3>
  <form action="{{ url_for('views.upload_data') }}" method="post" enctype="multipart/form-data">
    <input type="file" name="file" id="fileInput">
    <button type="submit">Upload</button>
  </form>
</div>
{% endblock %}